In [ ]:
import numpy as np
matrix = np.random.randint(1, 50, (10, 10))

print("Original Matrix:\n", matrix)
add_matrix = matrix + 10
print("\nMatrix after Addition (+10):\n", add_matrix)
sub_matrix = matrix - 5
print("\nMatrix after Subtraction (-5):\n", sub_matrix)
mul_matrix = matrix * 2
print("\nMatrix after Multiplication (*2):\n", mul_matrix)
div_matrix = matrix / 2
print("\nMatrix after Division (/2):\n", div_matrix)
transpose_matrix = matrix.T
print("\nTranspose of Matrix:\n", transpose_matrix)

Original Matrix:
 [[26 46 19 48 42  8  9 25 16 34]
 [44 15 31  5 42 12 49 18 32 47]
 [33  5 39 40 40 38 20 27  2 34]
 [30 42  9 17  7 23 22  4 45  2]
 [47 22 10 38 31 48 38 21  2 45]
 [29 14 10 43 30 47 22  1 49 15]
 [23 16  6 10 34 45 39 41 29  6]
 [21 17 13 33  6 24 46  3 38 23]
 [46 33 27 44  2 34  6  3 49 23]
 [12 20 22 10 25  5 20 22 29  9]]

Matrix after Addition (+10):
 [[36 56 29 58 52 18 19 35 26 44]
 [54 25 41 15 52 22 59 28 42 57]
 [43 15 49 50 50 48 30 37 12 44]
 [40 52 19 27 17 33 32 14 55 12]
 [57 32 20 48 41 58 48 31 12 55]
 [39 24 20 53 40 57 32 11 59 25]
 [33 26 16 20 44 55 49 51 39 16]
 [31 27 23 43 16 34 56 13 48 33]
 [56 43 37 54 12 44 16 13 59 33]
 [22 30 32 20 35 15 30 32 39 19]]

Matrix after Subtraction (-5):
 [[21 41 14 43 37  3  4 20 11 29]
 [39 10 26  0 37  7 44 13 27 42]
 [28  0 34 35 35 33 15 22 -3 29]
 [25 37  4 12  2 18 17 -1 40 -3]
 [42 17  5 33 26 43 33 16 -3 40]
 [24  9  5 38 25 42 17 -4 44 10]
 [18 11  1  5 29 40 34 36 24  1]
 [16 12  8 28  1 19 41 -2

**NumPy** is a powerful Python library used for numerical computing.
In this program, a **10×10 matrix** is created using numpy.random.randint().
Various arithmetic operations such as addition, subtraction, multiplication, and division are performed on the matrix elements.
The transpose operation converts rows into columns. These operations are commonly used in data analytics, machine learning, and scientific computing.

| Feature       | Power BI                                          | Tableau                                  |
| ------------- | ------------------------------------------------- | ---------------------------------------- |
| Developed By  | Microsoft                                         | Tableau Software (Salesforce)            |
| Ease of Use   | Easier for beginners                              | Slightly complex but powerful            |
| Integration   | Works well with Microsoft tools like Excel, Azure | Supports multiple data sources           |
| Cost          | Cheaper                                           | More expensive                           |
| Visualization | Good visualization                                | Very advanced and flexible visualization |
| Performance   | Best for small to medium datasets                 | Handles very large datasets efficiently  |


| Feature            | Microsoft Excel             | Google Sheets             |
| ------------------ | --------------------------- | ------------------------- |
| Platform           | Desktop application         | Cloud-based application   |
| Collaboration      | Limited collaboration       | Real-time collaboration   |
| Data Size Handling | Handles very large datasets | Limited compared to Excel |
| Offline Access     | Fully offline               | Mostly online             |
| Automation         | VBA macros supported        | Uses Google Apps Script   |
| Cost               | Paid software               | Free with Google account  |


| Feature        | MySQL                        | MongoDB                     |
| -------------- | ---------------------------- | --------------------------- |
| Database Type  | Relational Database          | NoSQL Database              |
| Data Storage   | Tables (Rows & Columns)      | JSON-like Documents         |
| Schema         | Fixed schema                 | Flexible schema             |
| Query Language | SQL                          | MongoDB Query Language      |
| Scalability    | Vertical scaling             | Horizontal scaling          |
| Best Use       | Structured data applications | Big data and real-time apps |
